{% set name = "fcgi2" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FastCGI-Archives/fcgi2/archive/refs/tags/{{ version }}.tar.gz
  sha256: c0e0d9cc7d1e456d7278c974e2826f593ef5ca555783eba81e7e9c1a07ae0ecc

build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - autoconf  # [unix]
    - libtool  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - gnuconfig   # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libfcgi${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/FastCGI-Archives/fcgi2
  summary: 'FastCGI implementation'
  description: |
    FastCGI Developers Kit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://github.com/FastCGI-Archives/fcgi2/
  dev_url: https://github.com/FastCGI-Archives/fcgi2/releases

extra:
  recipe-maintainers:
    - hobu
