{% set name = "fcgi2" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FastCGI-Archives/fcgi2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5273bc54c28215d81b9bd78f937a9bcdd4fe94e41ccd8d7c991aa8a01b50b70e
  patches:
    - patches/0001-support-x64-and-uwp-build.patch
    - patches/0002-get-2.4.2-compiling-on-windows.patch

build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - autoconf  # [unix]
    - libtool  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - gnuconfig   # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libfcgi${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/FastCGI-Archives/fcgi2
  summary: 'FastCGI implementation'
  description: |
    FastCGI Developers Kit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TERMS
  # The doc_url and dev_url are optional.
  doc_url: https://github.com/FastCGI-Archives/fcgi2/
  dev_url: https://github.com/FastCGI-Archives/fcgi2/releases

extra:
  recipe-maintainers:
    - hobu
